# Define an event consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-display
  namespace: eventing-test
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: classifier-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: classifier-display
          image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
kind: Service
apiVersion: v1
metadata:
  name: classifier-display
  namespace: eventing-test
spec:
  selector:
    app: classifier-display
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080