apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: classifier-display
  namespace: eventing-test
spec:
  broker: default
  subscriber:
    ref:
     apiVersion: v1
     kind: Service
     name: classifier-display # Service hello-display subscribes to the broker `default`